### ISSUE TITLE
editing image comment removes the image

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#10]
steps to reproduce:
1. Send an image from Discord to Matrix over the puppet. Add a comment to the image.
2. Edit this comment on Discord.

what I expected to happen:
On the Matrix side, the image would stay, the text under the image would change.

what actually happened:
On the Matrix side, the image was removed and replaced by the new comment.
![Screenshot_2019-09-18_00-20-45](https://user-images.githubusercontent.com/33424247/65083992-4bbf3280-d9aa-11e9-9c5a-889763da5425.png)

**Comment by Sorunome** [comment]
Good old "someone reported it in the help chat but was too lazy to make a ticket about this". Thanks for making a ticket!

**Comment by Sorunome** [comment]
fixed

**Comment by MRAAGH** [comment]
I am still able to reproduce this

**Comment by MRAAGH** [comment]
can not reproduce any more, it's fixed now, yay
