### ISSUE TITLE
when I have this bridge connected, I no longer receive notifications on my iPhone to the discord app

### ISSUE THREAD

**Issue by ericmigi** [matrix-discord/mx-puppet-discord#100]
Has anyone else experienced this issue? Discord mobile notifications are generally unreliable, but I've been able to replicate this one consistently

**Comment by Sorunome** [comment]
This is new to soru but she does not have an iOS device or use the official discord app, so yeah xP

**Comment by kliu128** [comment]
This also happens to me (on Android; messages never go through unless I shut off the bridge), but I treat it as a feature since I get notifications on Element instead :)

**Comment by ericmigi** [comment]
I think what would solve this is bridging presence - when you are not using a matrix client, the bridge could be 'away'

**Comment by Sorunome** [comment]
presence is bridged by now, so assuming that this is solved now.
