### ISSUE TITLE
 files with content-type audio/ogg are bridged to discord as .oga when they should be bridged as .ogg

### ISSUE THREAD

**Issue by blobcat-mewmew** [matrix-discord/mx-puppet-discord#102]
Pretty self-explanatory title. Discord's web client supports .ogg but not .oga files, so .ogg should be preferred as the file extension.

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/5aa18ed43cb16bcf31a28ce3f2cea7f3e1dcf855
