### ISSUE TITLE
Images either way are not relayed

### ISSUE THREAD

**Issue by chauffer** [matrix-discord/mx-puppet-discord#105]
Image embeds (sent directly to the chat, not a link) Discord>Matrix or Matrix>Discord do not get relayed at all.

**Comment by Sorunome** [comment]
What's your config.yaml?

28. 10. 2020 21:18:18 Simone Esposito <notifications@github.com>:

**Comment by chauffer** [comment]
I set mediaUrl wrong (by setting it at all).
Thanks for the hint and the quick response, and for the bridge. Other than
my configuration mistake, it works great!

I assumed this defaulted to https://matrix.to but I see it defaults to the
homeserver URL. Does it need to be publicly accessible? My home server runs
in kubernetes and the URL I've set is only internal to the cluster.

**Comment by Sorunome** [comment]
It needs to be publically accessible to make matrix->discord work properly. Some things may work without, avatars in relay mode won't for sure.

28. 10. 2020 21:56:23 Simone Esposito <notifications@github.com>:

> I set mediaUrl wrong (by setting it at all).
> Thanks for the hint and the quick response, and for the bridge. Other than
> my configuration mistake, it works great!
> 
> I assumed this defaulted to https://matrix.to but I see it defaults to the
> homeserver URL. Does it need to be publicly accessible? My home server runs
> in kubernetes and the URL I've set is only internal to the cluster.
>

**Comment by chauffer** [comment]
thank you. I've set mediaUrl to the public URL now.

**Comment by chauffer** [comment]
Is there a way for me to refresh the existing rooms to have the discord server images? I didn't know it was a feature of the bridge until now, and it'd be quite handy for all the chats I've already joined
