### ISSUE TITLE
Relay mode is unable to send message to Discord

### ISSUE THREAD

**Issue by CCF100** [matrix-discord/mx-puppet-discord#111]
If I enable relay mode with `settype 1 relay`, The relay will fail to send the message to Discord: 
![image](https://user-images.githubusercontent.com/29297989/99157945-18059880-2693-11eb-88e9-7497458eb3bc.png)
And will output this in the terminal:
![image](https://user-images.githubusercontent.com/29297989/99157961-3bc8de80-2693-11eb-97a8-cb6e73a6bc0a.png)

I can give more information if needed lol

**Comment by Sorunome** [comment]
You need at least node 12.

**Comment by Sorunome** [comment]
FYI the requirement may be bumped to node 14 soon

**Comment by CCF100** [comment]
Ah, I had the LTS package installed for some reason
