### ISSUE TITLE
Matrix->Discord quotes in text seem to break newlines

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#113]
Writing something like the following in Element Web:

```
> Here is something

That sure is a cool something

> Here is something else!

Oh no, I wasn't expecting that
```

yields this:

![image](https://user-images.githubusercontent.com/1342360/99920418-50544900-2d1b-11eb-983f-6a5ee059290c.png)

However, on the discord side, we see:

![image](https://user-images.githubusercontent.com/1342360/99920432-5ba77480-2d1b-11eb-9f47-86cec1cedda7.png)

The content of the event is:

```json
"content": {
    "msgtype": "m.text",
    "body": "> Here is something\n\nThat sure is a cool something\n\n> Here is something else!\n\nOh no, I wasn't expecting that",
    "format": "org.matrix.custom.html",
    "formatted_body": "<blockquote>\n<p>Here is something</p>\n</blockquote>\n<p>That sure is a cool something</p>\n<blockquote>\n<p>Here is something else!</p>\n</blockquote>\n<p>Oh no, I wasn't expecting that</p>\n"
  },
```

Anecdotally, I noticed that editing the message in Element Web gives you the following text to edit:

```
> Here is something

That sure is a cool something
> Here is something else!

Oh no, I wasn't expecting that
```

Notice the lack of double newline between `That sure is a cool something` and `> Here is something else!`. I don't know why this is, but it looks to be the same thing that's happening on the Discord side.

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/matrix-discord-parser/commit/1d94cdf2e8f38027df9f0ae4ffa07bfbf339b354
