### ISSUE TITLE
Reacting to an image will cause your Discord puppet user to join the room

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#114]
![image](https://user-images.githubusercontent.com/1342360/99976633-9c46d280-2d9b-11eb-8c67-12485419b2d2.png)

I'm using a user token. Reacting to a message will cause my Discord puppet user to join the room for some reason, even though it was my matrix user that sent the reaction.

**Comment by Sorunome** [comment]
it'll auto-leave after an hour.

reactions, redactions and typing all currently have an echo-back :/

**Comment by anoadragon453** [comment]
Ah huh ok, reactions were the only one I really noticed.

Is this possible to solve or something that can't fundamentally be fixed?

**Comment by Sorunome** [comment]
No, it can be solved ^^" And soru is sure there are about 900 issues about that open already >.< It just never bothered soru *that* much as it auto-left after an hour again

**Comment by anoadragon453** [comment]
Ah, OK!

> It just never bothered soru that much as it auto-left after an hour again

Yeah, I've actually known about this for months, but only reported it now since I was on a streak with the other issues. This is effectively just another issue to help polish the experience :>

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/7b80c5fbf356a55d7538d558913c9784acb0e050

**Comment by anoadragon453** [comment]
*gasp*, yay thank you Soru!
