### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by rakshazi** [matrix-discord/mx-puppet-discord#124]
Hello, i created new matrix homeserver and installed mx-puppet-discord, but I don't understand how to use it.

I created new discord app and bot, linked it to matrix (`link bot token` chat command), but how can I join any guild server? Command `acceptinvite 1 https://discord.gg/REDACTED` returns `Invalid invite code REDACTED: Bots cannot use this endpoint`

How can I send PM to and from the bot?
How can I join and chat in discord channels?

`bridgeguild` didn't work, too ( I suppose because I can't invite the bot to the guild)

Thank you for you work, but it misses (a bit) documentation for end users :)

**Comment by Sorunome** [comment]
you have to get discord guild admins to add your bot for you

**Comment by rakshazi** [comment]
Ok, i'm admin on one of the discord guilds, could you tell how can I invite the bot, please?

**Comment by Sorunome** [comment]
https://discordpy.readthedocs.io/en/latest/discord.html just tick all permissions that seem to make sense for normal chatting

**Comment by rakshazi** [comment]
ok, thank you!
Now i see how to use it
