### ISSUE TITLE
Bridge goes offline when I close the SSH Terminal

### ISSUE THREAD

**Issue by L-S-2020** [matrix-discord/mx-puppet-discord#128]
Hello, 
I have a problem, when I close the SSH Connection (via Putty) the bridge goes offline, so when I send help then, I don't get an answer. But when I connect via SSH again and type npm run start it works again.
How can I solve that problem, so that I can turn of my computer?
Thanks for help

**Comment by Sorunome** [comment]
you can use tmux, screen, systemd or multiple other methods. This question is out-of-acope for this repository, please research how to do basic system administration

16. 2. 2021 21:06:54 L-S-2020 <notifications@github.com>:
