### ISSUE TITLE
Can't send message to someone with a funny name

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#13]
Now sure if this is some other bug, but this bridge works fine except for someone who's got "S̷i̵l̷v̶e̷r̵" in their name. Log output is a bit sparse:

```
ep 23 23:09:24 server npm[32593]: Sep-23 23:09:24.983 [bot-sdk-Appservice] info: [ 'Processing transaction 483' ]
Sep 23 23:09:24 server npm[32593]: Sep-23 23:09:24.983 [bot-sdk-Appservice] info: [ 'Processing event of type m.room.message' ]
Sep 23 23:09:24 server npm[32593]: Sep-23 23:09:24.983 [PuppetBridge] verbose: got matrix event to pass on
Sep 23 23:09:24 server npm[32593]: Sep-23 23:09:24.984 [PuppetBridge] info: New message by @xxxxxxxxx:yyyyyyy.zzz of type m.room.message to process!
Sep 23 23:09:24 server npm[32593]: Sep-23 23:09:24.987 [DiscordPuppet:Discord] warn: Channel not found { roomId: 'dm-164412892530081692', puppetId: 1 }
```

**Comment by Sorunome** [comment]
Do you have a common guild with them?

**Comment by anoadragon453** [comment]
Ah, no.

**Comment by Sorunome** [comment]
That's the problem, then

Am 15. Oktober 2019 19:25:55 MESZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by anoadragon453** [comment]
Does discord.js disable that locally?

**Comment by Sorunome** [comment]
discord.js has no reliable way of fetching dm conversations with friends-only :/

Am 15. Oktober 2019 19:33:08 MESZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by anoadragon453** [comment]
But I get a message from a DM room. Surely when I post a matrix message in that room, you have a reference to the Discord room as well, and you can send a message in there?

**Comment by Sorunome** [comment]
You can send messages to friends now that you don't share a common guild with https://github.com/matrix-discord/mx-puppet-discord/commit/43fec82f3c8542c05d62850e3919f86e71f83ff8
