### ISSUE TITLE
Get Admin in Groups created by the puppet bridge

### ISSUE THREAD

**Issue by ottersarecool** [matrix-discord/mx-puppet-discord#133]
I let the bridge create groups for the servers my bot is in but the bridge is the only admin in there, I cannot add my friend to the group so he can also view the server from matrix, I tried `adminme` but the only output I get is `Room not resolvable`

**Comment by Sorunome** [comment]
unfortunately there is no api to give group admin, and there won't ever be one as groups will be replaced with spaces.

what this means, is, that it is impossible for this bridge to implement that, and literally the only way to be able to get admin in a group is by manually modifying synapse database.
