### ISSUE TITLE
Inviting back to direct message

### ISSUE THREAD

**Issue by Latrolage** [matrix-discord/mx-puppet-discord#139]
Lets just say I started an element channel bridge as direct message. But i accidentally leave the element channel. 

How would I join back to this channel?

This happened to me, and i couldn't find a way to join back. If it were to happen on a group chat or guild, would it be possible to join back through a command?

**Comment by Sorunome** [comment]
`invite <puppet id> <remote user id>` or `invite <ghost mxid>` or thelike

8. 5. 2021 8:05:28 Latrolage ***@***.***>:

**Comment by RoiArthurB** [comment]
Hello,
Sorry to restart this issue, but @Sorunome 's 2 commands doesn't work...

![image](https://user-images.githubusercontent.com/16764085/146325366-c00b0620-cda4-4732-b318-39faf7284472.png)
(I don't have any invitation pending if needed to say)

**Comment by RoiArthurB** [comment]
FIXED

My problem was that I did remove the room, but the bridge didn't remove the entry and tried to invite me in a missing room ID. Here's my fix : 
1. Create a new empty room 
2. Invite Discord Bot in and leave this room
3. Open your DB (me it's PostgreSQL)
4. Update wrong line `matrix_mx_puppet_discord=# UPDATE room_store SET "mxid"='!<NEW-ROOM-ID>:roiarthurb.xyz' WHERE "room_id"='dm-<puppet id>-<remote user id>';`
5. Relaunch `invite` command
6. Enjoy :)
