### ISSUE TITLE
Delete all discordpuppet users?

### ISSUE THREAD

**Issue by Latrolage** [matrix-discord/mx-puppet-discord#155]
How can I delete all the discordpuppet users and start over again. Or delete all users which aren't in any bridged channels? I accidentally bridged a large server and uhh there were lots of users

**Comment by Latrolage** [comment]
I ended up deleting all the entries from the database and uhh... hehe oops

**Comment by Sorunome** [comment]
Not sure what you are trying to ask. If you delete your own database then you suffer data loss (obviously).

**Comment by Latrolage** [comment]
I wanted to delete all the discordpuppet users. Deleting them through deleting them in the database did not fully delete them. Their names are still being resolved as normal usernames in element

**Comment by Sorunome** [comment]
the matrix protocol itself does not allow deleting users or ghosts.

**Comment by feydreva** [comment]
On your own home server, you can delete user  using  Synapse Admin

https://github.com/Awesome-Technologies/synapse-admin
