### ISSUE TITLE
Bridging Matrix to Discord

### ISSUE THREAD

**Issue by r1bnc** [matrix-discord/mx-puppet-discord#159]
is it possible to bridge matrix to discord and not the other way around?
Syncing Matrix rooms to discord.

TIA

**Comment by Sorunome** [comment]
not with this bridge, it doesn't dynamically create discord rooms. What you *can* do is bridge to existing rooms together, invite the bridge bot into the matrix room and run "!discord help". Be sure to enable self-service in your config.yaml

10. 7. 2021 9:41:34 Gian ***@***.***>:

**Comment by r1bnc** [comment]
Thanks, but it seems it won't work in my case. I was trying to bridge another bridge.
