### ISSUE TITLE
An extra user gets added for myself (i.e. mx-puppet-discord is not "double-puppeted"?)

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-discord/mx-puppet-discord#16]
When the following conditions are met:
User token
Message is sent from myself into a bridged dm room using the native discord client

Actual behavior:
mx-puppet-discord creates a 3rd bot user in the bridged matrix room with my discord user account name and records the message as being sent from that user. Because this "3rd user" (that isn't myself) sent the message, I also end up getting a new message notification in riot for a message that I had myself sent out from within discord. This doesn't make much sense, since I'm the one that sent the message I needn't be alerted to it.

Expected behavior:
It's preferred if mx-puppet-discord doesn't create a 3rd user and just sends the message from my own matrix user. This is in keeping with the behavior of a Double puppetted bridge - https://matrix.org/bridges/ Ctrl+f "Double-puppeting" - where both the discord and the matrix-side user gets puppetted.

I thought that the expected behavior was actually in place in commit d62e0b8, and at some point between d62e0b8 and eb1f581b the behavior changed. But I'm now not even able to replicate the expected behavior on the old d62e0b8 commit, so perhaps I'm imagining that it ever worked as expected in the first place.

**Comment by AndrewJDR** [comment]
I think perhaps I should be using `setmatrixtoken`?
that said, i just tried setmatrixtoken <access token from riot settings> and and I get back ERROR: Invalid matrix token. Looking at the puppet logs, i think it's trying to parse the html body of the message or something? because I see something like this in the bridge error log:
```
Sep-29 02:57:45.982 [bot-sdk-MatrixLiteClient] error: (REQ-1) { '0': '<',             
  '1': '!',                                                                                                                                                                   
  '2': 'D',                                                                                                                
  '3': 'O',                                                                                                     
  '4': 'C',                                                                                                                                                                   
  '5': 'T',                                                                
  '6': 'Y',                                                                                          
  '7': 'P',                                                                             
  '8': 'E',                                                                                          
  '9': ' ',                                                               
  '10': 'H',                                                                          
  '11': 'T',                                                                                                                                                                  
  '12': 'M',                                                              
```

**Comment by Sorunome** [comment]
Can you post more logging around that when you attempt `setmatrixtoken`?

**Comment by AndrewJDR** [comment]
```
  express:router dispatching PUT /transactions/1332?access_token=xxx +15s
  express:router query  : /transactions/1332?access_token=xxx +1ms
  express:router expressInit  : /transactions/1332?access_token=xxx +1ms
  express:router jsonParser  : /transactions/1332?access_token=xxx +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
  express:router logger  : /transactions/1332?access_token=xxx +0ms
Sep-29 07:32:05.543 [bot-sdk-Appservice] info: Processing transaction 1332
Sep-29 07:32:05.543 [bot-sdk-Appservice] info: Processing event of type m.room.message
Sep-29 07:32:05.546 [BotProvisioner] info: Got message to process with arg=setmatrixtoken
  morgan log request +12ms
127.0.0.1 - - [29/Sep/2019:07:32:05 +0000] "PUT /transactions/1332?access_token=xxx HTTP/1.1" 200 2 "-" "Synapse/1.3.1 (b=develop,ad64e90ed)"
  express:router dispatching PUT /transactions/1333?access_token=xxx +177ms
  express:router query  : /transactions/1333?access_token=xxx +0ms
  express:router expressInit  : /transactions/1333?access_token=xxx +1ms
  express:router jsonParser  : /transactions/1333?access_token=xxx +0ms
  body-parser:json content-type "application/json" +1ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +1ms
  body-parser:json parse body +0ms
  body-parser:json parse json +1ms
  express:router logger  : /transactions/1333?access_token=xxx +0ms
Sep-29 07:32:05.736 [bot-sdk-Appservice] info: Processing transaction 1333
Sep-29 07:32:05.736 [bot-sdk-Appservice] info: Processing event of type m.room.message
  morgan log request +2ms
127.0.0.1 - - [29/Sep/2019:07:32:05 +0000] "PUT /transactions/1333?access_token=xxx HTTP/1.1" 200 2 "-" "Synapse/1.3.1 (b=develop,ad64e90ed)"
Sep-29 07:32:05.980 [bot-sdk-MatrixLiteClient] error: (REQ-1) { '0': '<',
  '1': '!',
  '2': 'D',
  '3': 'O',
  '4': 'C',
  '5': 'T',
  '6': 'Y',
  '7': 'P',
  '8': 'E',
  '9': ' ',
  '10': 'H',
  '11': 'T',
  '12': 'M',
  '13': 'L',
  '14': ' ',
  '15': 'P',
  '16': 'U',
...
  '295': '<',
  '296': '/',
  '297': 'h',
  '298': 't',
  '299': 'm',
  '300': 'l',
  '301': '>',
  '302': '\n' }
  express:router dispatching PUT /transactions/1334?access_token=xxx +488ms
  express:router query  : /transactions/1334?access_token=xxx +1ms
  express:router expressInit  : /transactions/1334?access_token=xxx +0ms
  express:router jsonParser  : /transactions/1334?access_token=xxx +1ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +1ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
```

**Comment by Sorunome** [comment]
Do you, by any chance, need a different homeserverURL than the one in your matrix ID and have *not* .well-known set up? If so, that'd be it

**Comment by AndrewJDR** [comment]
Yes indeed! Thanks. I will take a look at setting up well-known. Last time I looked into this situation, matrix was still using SRV records for this purpose.

**Comment by Sorunome** [comment]
SRV records were never used for client-sided stuffs, only for federation

**Comment by AndrewJDR** [comment]
Oh okay. I only knew .well-known as a potential replacement for SRV records at some point, so it seems clueless about what .well-known is used for these days.

I'll look into it though, thanks!

**Comment by AndrewJDR** [comment]
I more recently got well-known set up properly but I'm still seeing the behavior described in my original post here. I confirmed well-known is working using riot -- during login it now auto-populates my correct home server url, with its non-standard port.

Just to recap the issue:
I'm doing double-puppetting with a user token, and in a DM room, if i send a message using the official Discord client, when i look in the corresponding matrix room, it shows as being sent from a 3rd "__discordpuppet" bot user rather than being sent from my actual user account (which it should be puppetting as).

Here's what is shown in the mx-puppet-discord output when I send a message using the official client into the DM room:
```
Mar-9 05:28:17.608 [DiscordPuppet:DiscordEventHandler] info: Received new message!
Mar-9 05:28:17.610 [RemoteEventHandler] info: Received message from 620550060622xxxxxx to send to dm-424777913xxxxxxxxx
Mar-9 05:28:17.611 [UserSync] info: Fetching client for 620550060622xxxxxx
Mar-9 05:28:17.612 [Util] info: Processing profile update...
Mar-9 05:28:17.613 [bot-sdk-MatrixLiteClient] info: (REQ-4) PUT http://localhost:8008/_matrix/client/r0/rooms/!ZVDrSJGfUTxxxxxxxxxxxxxxxxxxxxxx/send/m.room.message/xxxxxxxxx7613__REQ3
Mar-9 05:28:17.778 [bot-sdk-Appservice] info: Processing transaction 5498
Mar-9 05:28:17.779 [bot-sdk-Appservice] info: Processing event of type m.room.message
127.0.0.1 - - [09/Mar/2020:05:28:17 +0000] "PUT /transactions/5498?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 200 2 "-" "Synapse/1.11.1 (b=develop,xxxxxxxxx)"
```

Not sure where to go from here, but I'm happy to add more debug prints if you point me in the right general direction...

**Comment by Sorunome** [comment]
dud you run "setmatrixtoken $yourToken" yet?

Am 9. März 2020 06:36:46 MEZ schrieb Andrew Johnson <notifications@github.com>:

**Comment by AndrewJDR** [comment]
@Sorunome Ah, looks like my old token went bad. Working now, thanks!
