### ISSUE TITLE
How does the setmatrixtoken command work?

### ISSUE THREAD

**Issue by Latrolage** [matrix-discord/mx-puppet-discord#160]
I want to get the bot to be able to send messages as my user, but it doesn't seem to be documented anywhere I can find?

Since it's not documented, how safe you would you say it is to do it, (will it like break my account or do any other weird things or make my account less secure/private?)

Also where's the token I'm supposed to get?

sry if this is documented, i couldn't find it in the main readme

**Comment by Latrolage** [comment]
by the way, is it possible to use this for a room in which both users use discord, but they want to be able to continue the conversation on the matrix server.

Like a full duplicate of the conversation, with the bot sending stuff from each person's respective accounts on each platform so that they can communicate from any platform to one another?

**Comment by Sorunome** [comment]
for double puppeting either use `setmatrixtoken <access token>` (you can get your access token e.g. in element-web settings) or configure [automated double-puppeting](https://github.com/Sorunome/mx-puppet-bridge#plumbed-rooms)

multiple people can use one bridge and it'll automatically deduplicate rooms on the matrix side

13. 7. 2021 12:18:55 Latrolage ***@***.***>:
