### ISSUE TITLE
Editing message twice removes message content

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#17]
Steps to reproduce:
- send a message from Discord to Matrix
- edit this message on Discord
- edit this message on Discord again
- send a message from Matrix to Discord

What I expected to happen:
- the message from Discord gets updated twice

What actually happened:
- the message from Discord gets updated only once. Then it becomes empty.

**Comment by Sorunome** [comment]
that might actually be a riot-web bug

Am 3. Oktober 2019 10:48:11 MESZ schrieb MRAAGH <notifications@github.com>:

**Comment by MRAAGH** [comment]
Indeed, there seems to be a bug in riot-web when editing the same message twice. But it does not seem to be the same bug; messages aren't completely disappearing as far as I can tell.

**Comment by MRAAGH** [comment]
Still exists

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/0c3c0b4eed9e7a1ceb26ba9ce251bbaa61efd2b8

Also, please don't post "still exists" updates.
