### ISSUE TITLE
You do not have permission to post to this room

### ISSUE THREAD

**Issue by Poisonsting** [matrix-discord/mx-puppet-discord#171]
Recently, my Discord account was disabled for suspicious activity due to a combination of using my user token, my server internet going down, and having no documentation to figure out how to relink an existing user.

I've since managed to relink the account and get DMs working as expected, but now I have Custom (-1) permissions in all group chats.

Any ideas for what I might try to fix the issue?

**Comment by kittywitch** [comment]
Same issue with disabled for suspicious activity and so on, this is a crackdown by Discord on custom clients.

**Comment by Just-Insane** [comment]
This also started happening to me.

I’d try using a bot account, but you can’t directly DM them, and asking people to add them to servers isn’t great.

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/171
