### ISSUE TITLE
Command to generate a link to add a Discord bot to guild

### ISSUE THREAD

**Issue by fflorent** [matrix-discord/mx-puppet-discord#176]
matrix-appservice-discord used to implement a command to easily generate a link so we can add a bot to a Discord guild with the relevant rights:

https://github.com/Half-Shot/matrix-appservice-discord/blob/316cd58066fc272cea6abe596d8955fd1d940f56/src/util.ts#L109-L125

I think that's convenient and would be a good fit in the README steps right after the application creation (especially for those who are not used to Discord).

The `clientId` seem to be available through the expression `client.user.id` (where `client` is a `Discord.Client`).

If the feature request seems to you valid, I would be glad to work on it.

**Comment by spantaleev** [comment]
I was also wondering how I could get such a link with mx-puppet-discord.

Seems like the README only describes how to use the bridge in a way that violates Discord's ToS and gets your account disabled (see #171).

**Comment by fflorent** [comment]
The invitation link is of this form:

`https://discord.com/api/oauth2/authorize?client_id=${clientId}&scope=bot&permissions=${perms}`

You can value permission to 535327931456 which corresponds to these permissions:
![image](https://user-images.githubusercontent.com/371705/133581674-b9176eef-9d6e-44f7-b761-e172a4dcbe52.png)

However, I wonder if all these rights are relevant.

**Comment by fflorent** [comment]
NB: `Send TTS messages` should rather be disabled.

**Comment by TheDiscordian** [comment]
> If the feature request seems to you valid, I would be glad to work on it.

I would like to see this feature, and I'd be willing to bet a PR would be welcome (but not my call).

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/176
