### ISSUE TITLE
Add setting to enable only discord -> matrix presence

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-discord/mx-puppet-discord#178]
Is it possible to not send presence to discord while still receiving presence from it? I think discord would (if I were to use a user token) still know that I am present since the bridge is syncing at all, right?

Either way I'd prefer to appear "invisible" offline on discord.

Would you consider such a feature/setting/interactive user setting?

Continuing that thought, it would be nice if the current presence setting wasn't (only) a global bridge setting but also a user customizable setting.

actually perhaps this issue is more relevant to mx-puppet-bridge, lmk.

**Comment by HarHarLinks** [comment]
The setting `de.sorunome.msc2409.push_ephemeral: true` inthe registration.yaml probably influences the presence behaviour

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/178
