### ISSUE TITLE
Add option to disable uploading images to homeserver

### ISSUE THREAD

**Issue by puyoxyz** [matrix-discord/mx-puppet-discord#181]
As far as I can see there's no way to not upload images to the homeserver (and instead just put the Discord CDN link in the message). I don't really want every single Discord image I receive to be stored on my homeserver.

([here?](https://github.com/matrix-discord/mx-puppet-discord/blob/bb6438a504182a7a64048b992179427587ccfded/src/discord/DiscordEventHandler.ts#L87))

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/181
