### ISSUE TITLE
Element breaking because of flood of "notice_member_no_changes"

### ISSUE THREAD

**Issue by Notmarrco** [matrix-discord/mx-puppet-discord#185]
Hi,
I cannot access my rooms with element anymore because there is thousands of "status changes" in the room and element crashes before loading everything. The changes are seen by Element as "notice_member_no_changes". It means i'm just flooded with "xxx made no changes" messages.
I can still access my room using eg Fractal, but some messages are missing, so it seems like the flood also affects the perfs of dendrite.

I thought it was due to the bridge sending/receiving presence, but I disabled the presence in the config, did an install from scratch and the issue persisted. Is there another event I should disable ?

Thank you for your help.

**Comment by Notmarrco** [comment]
Is there anything I could do ?
I'm under the impression that the presence is still bridged even if I disable it in the config.
I tried to debug but I didn't find anything. Any pointer please ?

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/185
