### ISSUE TITLE
Configuring bridge to use Matrix user address in Discord

### ISSUE THREAD

**Issue by Ryonez** [matrix-discord/mx-puppet-discord#186]
One of the things I've noticed is that there doesn't seem to be any way to configure what username is used for the webhooks in Discord.
This leads to a potential issue as display names in Matrix aren't unique, meaning users with the same display name won't clearly be marked differently in Discord.

Discord to Matrix isn't an issue, and the bridge places the discord user id in the Matrix address it give the user.

Is there an undocumented method to change this?

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/186
