### ISSUE TITLE
PuppedID Not Found

### ISSUE THREAD

**Issue by lgwapnitsky** [matrix-discord/mx-puppet-discord#187]
I've had this running for a while, but I noticed my discord rooms were very quiet. I still have the bot running, and it appears to work, but I can't join any rooms, etc, without getting "PuppedID not found".

Advice welcome

**Comment by marckrieger** [comment]
Have you tried linking your user account instead of the bot account? WIth the bot account you have to be invited by the server admins on discord first, I believe. With the user account everything should be linked out of the box, rooms and PMs.

**Comment by Chickensoupwithrice** [comment]
I'm running into the same issue. I configured mx-puppet-discord using a user account, and now none of my chats update, and when I talk to the discord bot my account is still linked but none of the rooms show up, it only shows the linked ID and nothing else. Not sure what went wrong?

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/187
