### ISSUE TITLE
Warn if you can't send a message to a Discord user

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#20]
If a user sends you a message and they don't share a server with you, `discord.js` will prevent you from responding because it's meant to be a bot library, and bots aren't able to DM users in this situation.

If a user sends you a DM and you can't respond, the bridge should create a room that you can't post to, as well as posting an initial message to state that you will need to respond on Discord.

On every new message from a user, check the state of whether the user can reply, and un/lock the room and post a message if the state has changed.

**Comment by Sorunome** [comment]
no way to lock the room if you created it yourself b* initiating conversation from the matrix side... :/

Am 15. Oktober 2019 19:39:10 MESZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by anoadragon453** [comment]
I didn't even know you could initiate from the matrix side...?

In all my DM rooms the ghost user is the admin.

**Comment by Sorunome** [comment]
`listusers` and then click on a pill / invite them to a new direct room

Am 15. Oktober 2019 19:51:59 MESZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by anoadragon453** [comment]
Well, then just posting a notice when the user tries to talk to a ghost that can't be spoken to is enough.

**Comment by Sorunome** [comment]
So as of https://github.com/matrix-discord/mx-puppet-discord/commit/43fec82f3c8542c05d62850e3919f86e71f83ff8 is this even needed?

**Comment by Sorunome** [comment]
Oh, wait, you can still be e.g. blocked by the other person or they don't have that sending DMs is enough to have a common guild and you aren't a friend.

Who/how should such a warning be sent, then?

**Comment by anoadragon453** [comment]
> Who/how should such a warning be sent, then?

When you try to send them a message in a PM just send a `m.notice` back from them that says "A message cannot be sent to this user: <reason>".

Similar to how @tulir's bridges do it.

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/c3779d6f168806ed6f2aa7a3a7b72ce5d2d13a77
