### ISSUE TITLE
better-discord.js dependency requires github ssh login

### ISSUE THREAD

**Issue by Kunsi** [matrix-discord/mx-puppet-discord#201]
Hi,

https://github.com/matrix-discord/mx-puppet-discord/blob/master/package-lock.json#L531

Having a `ssh://git@github.com` in there requires the user to have a working github ssh login on the system where the bridge will be running. This should be changed to a `https` link instead.

**Comment by dsonck92** [comment]
Using a higher version for NPM should also fix this, using `>=8`

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/201
