### ISSUE TITLE
Some bridged discord users are not invited to matrix rooms

### ISSUE THREAD

**Issue by Traace** [matrix-discord/mx-puppet-discord#207]
Hi, I just installed mx-puppet-discord together with a fresh synapse server. Afterwards I bridged two guilds.

I have the problem that not every Discord user got invited to the linked matrix rooms, it seems like the bot tries to invite them but it fails. Many of this actions get logged which leads to a 1,5GB log size every day.

Any suggestions on this?

Here are some logs (multiple rooms and users are affected from this issue)

`Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.759 [bot-sdk-MatrixLiteClient] #033[32minfo#033[39m: (REQ-34) PUT http://matrix-synapse:8008/_matrix/client/r0/rooms/!UUSskcYvVUZMXlRfzn%3Afopnu.pw/state/m.room.member/%40_discordpuppet__925399527853273109%3Afopnu.pw
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.762 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.763 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 910600908738551838...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.763 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.764 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 901024765245018132...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.765 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.765 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 894676228898967552...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.766 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.766 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 901023658347225128...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.767 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.767 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 900420386276130887...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.769 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.769 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 922798043009540116...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.770 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.770 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 941445756970205264...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.771 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.771 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 894677158130249738...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.772 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.772 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 936652094289629244...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.773 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.773 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 938446780624945262...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.774 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.774 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 941038733350830140...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.776 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.776 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 937097043208450048...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.777 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.777 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 885038923418591273...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.779 [bot-sdk-MatrixLiteClient] #033[31merror#033[39m: (REQ-24) {"errcode":"M_FORBIDDEN","error":"You are not invited to this room."}
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.780 [ReactionHandler] #033[32minfo#033[39m: Received reaction from 925399527853273109 to send to 795657264975446020, message 958324263448887326
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.782 [bot-sdk-MatrixLiteClient] #033[31merror#033[39m: (REQ-25) {"errcode":"M_FORBIDDEN","error":"You are not invited to this room."}`

`Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.809 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 894213908087312394...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.809 [bot-sdk-MatrixLiteClient] #033[32minfo#033[39m: (REQ-36) PUT http://matrix-synapse:8008/_matrix/client/r0/rooms/!tbzHkwyDQNiYsPJmot%3Afopnu.pw/state/m.room.member/%40_discordpuppet__925399527853273109%3Afopnu.pw
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.815 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.815 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 795657262910668875...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.816 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.817 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 947407707281973289...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.818 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.818 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 937068082273329193...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.819 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.820 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 924991264775106570...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.821 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.821 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 827253879661133874...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.824 [Util] #033[32minfo#033[39m: Updating new display name
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.824 [UserSync] #033[32minfo#033[39m: Setting room override for puppet 2 925399527853273109 in 795657268871430164...
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.827 [UserSync] #033[32minfo#033[39m: Fetching client for -1
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.828 [UserSync] #033[32minfo#033[39m: old user info 925399527853273109
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.829 [UserSync] #033[32minfo#033[39m: no property name exists for 925399527853273109
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.830 [RoomSync] #033[32minfo#033[39m: Fetching mxid for roomId 795657264975446020 and puppetId -1
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.832 [ReactionHandler] #033[32minfo#033[39m: Removing reaction from 925399527853273109 in 795657264975446020, message 958324263448887326
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.834 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.835 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.836 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.837 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.837 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.838 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.839 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.840 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.841 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.842 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.843 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.843 [UserSync] #033[33mwarn#033[39m: Room MXID not found
Mar 29 13:48:01 matrix matrix-mx-puppet-discord[19162]: Mar-29 11:48:01.844 [UserSync] #033[33mwarn#033[39m: Room MXID not found`

**Comment by Salastil** [comment]
It seems like this project is abandoning Github in favor of Gitlab and I filed something similar over there: https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/205

**Comment by dsonck92** [comment]
Thanks for simplifying my work! Yes, tracked by the issue noted above. I will close all issues on github and point to their related gitlab issues.
