### ISSUE TITLE
Group DM support

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-discord/mx-puppet-discord#21]
Currently, messages in group DM channels yield this log entry:
```
Only handling DM channels, dropping message
```

Might it be possible to support group DM channels with puppetting?

**Comment by MRAAGH** [comment]
I think this is the same as #18

**Comment by Sorunome** [comment]
> I think this is the same as #18

no, group DMs and guild text channels are two different things

**Comment by Sorunome** [comment]
Added in https://github.com/matrix-discord/mx-puppet-discord/commit/ead753d43e8e9f44dda7a4eaee7df0851d344ddd
