### ISSUE TITLE
setmatrixtoken attempts to connect through a different port

### ISSUE THREAD

**Issue by BrainDamage** [matrix-discord/mx-puppet-discord#22]
my use case is a private matrix server that's connected by me and not part of the federation, so I don't have TLS or DNS setup
config.yaml has:
```
bridge:
  # Port to host the bridge on
  # Used for communication between the homeserver and the bridge
  port: 8434
  # The host connections to the bridge's webserver are allowed from
  bindAddress: localhost
  # Public domain of the homeserver
  domain: alarmserver.local
  # Reachable URL of the Matrix homeserver
  homeserverUrl: http://localhost:8008
```
the domain is a mdns name, which resolves to the link-local address of the VPN

everything works so far ( and works even with other double sock puppet bridges such as mautrix-whatsapp )
except when I try to double sock puppet by issuing setmatrixtoken I get:

```
Dec 05 13:59:34 alarmserver npm[5144]: Dec-5 13:59:34.833 [bot-sdk-Appservice] info: Processing event of type m.room.message
Dec 05 13:59:35 alarmserver npm[5144]: Dec-5 13:59:34.842 [BotProvisioner] info: Got message to process with arg=setmatrixtoken
Dec 05 13:59:35 alarmserver npm[5144]: 127.0.0.1 - - [05/Dec/2019:13:59:35 +0000] "PUT /transactions/51?access_token=SNIP HTTP/1.1" 200 2 "-" "Synapse/1.5.1"
Dec 05 13:59:42 alarmserver npm[5144]: Dec-5 13:59:42.372 [bot-sdk-MatrixLiteClient] error: (REQ-1) Error: connect ECONNREFUSED 169.254.1.1:443
Dec 05 13:59:42 alarmserver npm[5144]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16) {
Dec 05 13:59:42 alarmserver npm[5144]:   errno: -111,
Dec 05 13:59:42 alarmserver npm[5144]:   code: 'ECONNREFUSED',
Dec 05 13:59:42 alarmserver npm[5144]:   syscall: 'connect',
Dec 05 13:59:42 alarmserver npm[5144]:   address: '169.254.1.1',
Dec 05 13:59:42 alarmserver npm[5144]:   port: 443
Dec 05 13:59:42 alarmserver npm[5144]: }
Dec 05 13:59:49 alarmserver npm[5144]: Dec-5 13:59:49.891 [bot-sdk-Appservice] info: Processing transaction 52
Dec 05 13:59:49 alarmserver npm[5144]: Dec-5 13:59:49.893 [bot-sdk-Appservice] info: Processing event of type m.room.message
Dec 05 13:59:49 alarmserver npm[5144]: 127.0.0.1 - - [05/Dec/2019:13:59:49 +0000] "PUT /transactions/52?access_token=SNIP HTTP/1.1" 200 2 "-" "Synapse/1.5.1"
```
the IP is the DNS resolution of alarmserver.local, which is a valid IP the server is listening on, but port 443 is not and I don't understand why it's attempting to use the TLS port when I haven't set up for such

**Comment by Sorunome** [comment]
Maybe you have an incorrevtly set up .well-known file?

Am 5. Dezember 2019 15:21:24 MEZ schrieb BrainDamage <notifications@github.com>:

**Comment by BrainDamage** [comment]
I don't have a .well-known file, at least, none I've setup myself. That http server is synapse's builtin. I've tried querying it directly to see if it'd respond to a .well-known path but it answers with 404.

**Comment by Sorunome** [comment]
that'd be the problem, then. You configire custom ports via configuring .well-known

Am 5. Dezember 2019 19:20:12 MEZ schrieb BrainDamage <notifications@github.com>:

**Comment by BrainDamage** [comment]
Sorry, I don't understand the process here.
The mx-puppet-discord connects to synapse through   homeserverUrl: http://localhost:8008
and synapse connects back to the service through bindAddress: localhost   port: 8434
Why would any further information be necessary? 
No other appservice mechanism I've configured used further information. 
It knows already that the alarmserver.local domain is reachable through the server at http://localhost:8008

**Comment by Sorunome** [comment]
mx-puppet-discord acts as a *client* here, and thus you need to set up `.well-known` correctly to have non-default configurations to work properly.

**Comment by Sorunome** [comment]
Additional config options have been added that will work for you: homeserver URL mapping. Add the following:

```yaml
homeserverUrlMap:
  alarmserver.local: http://localhost:8008
```

or use the IP or whatever you are using for the mapping
