### ISSUE TITLE
Support for custom emotes as reactions

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#23]
When reacting with a custom emote on Discord, the emote does not appear on Matrix. It only shows as text.

![Screenshot_2019-12-24_13-51-50](https://user-images.githubusercontent.com/33424247/71413895-92c95d80-2654-11ea-9147-5af2828af04c.png)

**Comment by Sorunome** [comment]
This is impossible as matrix does not support custom image reactions.

**Comment by Sorunome** [comment]
They are bridged as mxc uris for now, some clients like riotpony actualy display them correctly, then

**Comment by Jab2870** [comment]
I just thought it would be worth bringing to your attention a proposal to add
custom emoji and sticker packs to matrix.

https://github.com/matrix-org/matrix-doc/pull/1951

**Comment by Sorunome** [comment]
this bridge follows https://github.com/matrix-org/matrix-doc/pull/2545

4. 5. 2021 12:18:24 Jonathan ***@***.***>:
