### ISSUE TITLE
Editing message on Matrix causes a new puppet to join the room

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#24]
Steps to reproduce:
- Start with a freshly bridged room
- Send a message from Matrix to Discord
- Edit this message on Matrix

What I expected to happen:
The message changes on Matrix and on Discord.

What actually happened:
The message changes on Matrix and on Discord. Then, a new member of the room appears on Matrix, and you can't get rid of this in any other way than leaving and rejoining the room on Matrix.

Screenshot:
![Screenshot_2019-12-24_14-02-21](https://user-images.githubusercontent.com/33424247/71414556-cc4f9800-2657-11ea-88d2-8685288fa195.png)

**Comment by Sorunome** [comment]
the real bug here is that the edit gives an echo back to matrix

**Comment by MRAAGH** [comment]
If you mean the `(edited on Matrix)`, I actually added that manually. Sorry if that made it confusing!

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/07df603c89863f97a2e21e8696de01eab395e7b2

**Comment by MRAAGH** [comment]
I confirm it is fixed. Yay!
