### ISSUE TITLE
use discord guild avatar as matrix room avatar

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#25]
It would be nice to set the avatar of a bridged guild also as room avatar for the corresponding matrix rooms.
Currently it sets no avatar as far as I can see.

**Comment by Sorunome** [comment]
The discord guild icon is supposed to be used as matrix room icon and it is working over here. Does your guild perhaps have an animated icon or thelike?

**Comment by lub** [comment]
No, they are not animated.

There is an error while uploading the image, probably because of https://github.com/matrix-org/synapse/issues/6444#issuecomment-569973710 as matrix-bot-sdk has a default filename of null.

I'm honestly not sure what is causing the bug here. matrix-bot-sdk sending an empty filename, synapse handling it incorrectly or both.

I've applied a small fix to my local matrix-bot-sdk (`filename: string = 'file'` instead of `filename: string = null`) and it now correctly sets the avatar. So I don't think it should be a bug in mx-puppet-discord.

**Comment by Sorunome** [comment]
Sounds like the proper fix would be to add a filename [here](https://github.com/Sorunome/mx-puppet-bridge/blob/master/src/util.ts#L131)? Oddly enough that is the same code that is responsible for e.g. uploading user avatars and that works fine?

**Comment by lub** [comment]
Now that you wrote it, user avatars also didn't work. I just haven't noticed this, because it worked until synapse 1.4.1 and the old avatars were still displayed.
I only noticed the missing room avatars when I started testing the guild bridging.

**Comment by pot8to** [comment]
Can confirm, I set up a new bridge just a few days ago and I haven't gotten either user avatars or room avatars.

**Comment by Sorunome** [comment]
Does it work now?

**Comment by pot8to** [comment]
User avatars seem to work now with the latest commit. I would expect room avatars to do the same (although I'm not sure how to trigger them to update).

**Comment by Sorunome** [comment]
You could empty the `avatar_url`, `avatar_mxc` and `avatar_hash` columns in the `chan_store` table and restart the service

**Comment by pot8to** [comment]
Yup, can confirm that guild avatars work as well now.

**Comment by Sorunome** [comment]
Great, thanks for testing!
