### ISSUE TITLE
Give admin permissions in bridged room

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#26]
In every bridged chat, I noticed, the discordpuppet is an admin, while I am merely default power level. I find this strangely restrictive. Is there a reason why we don't want to allow the user to mess with the room's settings and members?

**Comment by Sorunome** [comment]
Why would you want to add users?

Am 26. Dezember 2019 12:37:02 MEZ schrieb MRAAGH <notifications@github.com>:

**Comment by MRAAGH** [comment]
I might want to change the room name, maybe even the picture in some cases. And if strange things happen, such as when ghost users joined because of #24, I could have removed them manually if I had access to that functionality. I think it's nice to be able to manually fix things if something's wrong.

Do you think this would add too much room for mistakes?

**Comment by AndrewJDR** [comment]
As mentioned over on #58, it'd be nice to be able to change room names, and lack of admin privileges on the room prevents this from happening. If that's tough to do, another alternative would be introduce some commands to ask the bot to set certain room params (e.g. `setroomname <matrix room id>`
