### ISSUE TITLE
unable to rejoin exit'ed rooms

### ISSUE THREAD

**Issue by BrainDamage** [matrix-discord/mx-puppet-discord#28]
To reproduce:
* enable room bridging for a guild
* list the channels
* join a channel
* accept confirmation
* exit the room
* accept confirmation
* try to rejoin the room in the channel list

log has:

```
   toJSON: [Function: responseToJSON],
   caseless: Caseless {
     dict: {
       connection: 'close',
       server: 'Synapse/1.7.3',
       date: 'Wed, 01 Jan 2020 19:02:46 GMT',
       'content-type': 'application/json',
       'content-length': '62',
       'cache-control': 'no-cache, no-store, must-revalidate',
       'access-control-allow-origin': '*',
       'access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS',
       'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
     }
   },
   body: { errcode: 'M_ROOM_IN_USE', error: 'Room alias already taken' },
   [Symbol(kCapture)]: false
 }
```
which makes me think the room was not deleted and the bot attempts to recreate it instead of rejoining if the name exits

looking at synapse bugtracker, it seems it doesn't reap empty rooms automatically:
https://github.com/matrix-org/synapse/issues/1307
https://github.com/matrix-org/synapse/issues/4720

not sure if you want to delete manually the existing room, attempt to rejoin it, or just wait when/if upstream fixes it

**Comment by Sorunome** [comment]
Apparently there is no code to un-register the alias, must have been an oversight!

**Comment by Sorunome** [comment]
Fixed it in https://github.com/matrix-discord/mx-puppet-discord/commit/b4df0ab552130324fb099f620d49931919724f10

To manually remove an alias run `delete from room_aliases where room_alias = '#_discordpuppet_that_alias:yourserver.com';` in the synapse DB
