### ISSUE TITLE
Ability to add friends, view existing ones and see pending friend requests

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#3]
Some commands to manage your friends and friends list from the bot would be super handy.

Something like:

* `friends` to view a list of pending friend requests, and your existing friends and their online status
* `addfriend` to send a friend request

**Comment by Sorunome** [comment]
Unfortunately this isn't a feature of discord.js due to user tokens being against discords ToS

**Comment by Sorunome** [comment]
So, soru tried implementing this and in the process of doing so her test account got a soft-lockdown (somehow can only accept/invite friends from the webbrowser, not the bot. It keeps asking for email verification codes) and when trying to make new test accounts they get a hard lockdown (it is asking for phone verification).

Is it worth implementing this? Soru *thinks* she has a working version atm but it may lock down your account, so she isn't sure if she should publish it

**Comment by Sorunome** [comment]
Added it behind an enabling wall. Readme is updated with instructions

**Comment by Ezwen** [comment]
Sorry to comment on a closed issue, but quick question: you explain that softlocks occur when trying to accept/invite friends, but do we know how risky it is atm to use this bridge if one never accept/invite friends and only talk with existing friends?

**Comment by Sorunome** [comment]
With an update later on it appears that the softlocks are resolved (better impersinating of a browser), soru left the warning in just in case. Soru herself uses friends management just fine and knows of a few others who use it.

Please note, soru does *not* take any responsibility for if your account gets locked or anything.

**Comment by Ezwen** [comment]
> With an update later on it appears that the softlocks are resolved (better impersinating of a browser), soru left the warning in just in case. Soru herself uses friends management just fine and knows of a few others who use it.

Good to know, thanks!

> Please note, soru does _not_ take any responsibility for if your account gets locked or anything.

Of course :)

> > but do we know how risky it is atm to use this bridge if one never accept/invite friends and only talk with existing friends?
> 
> And that shouldn't really be risky at all, beyond the usual "you are using a usertoken"

Great, I'll give it a try then. 

Thank you for answering!
