### ISSUE TITLE
Better display of invites to a guild room

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#30]
![image](https://user-images.githubusercontent.com/1342360/71707598-ccb70400-2db8-11ea-854b-d23b4cb2bbe9.png)

When you receive an invite to the room of a guild, you are presented to an invite to some discord user. I believe it's possible to customize the information displayed in the invite, so it may be nice to set that to the name of the guild/room.

**Comment by Sorunome** [comment]
huh, somehow room name is only set after the creation call, causing this bug.

**Comment by anoadragon453** [comment]
Ah, is this a Synapse bug or a bridge one?

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/b9744ab1b250b9ba1781a47c637d0802878bcca3
