### ISSUE TITLE
Immediately invite user to all rooms of a guild upon bridging

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#31]
When bridging a guild, it's kind of annoying to have to wait until a message is sent in each room before you can participate in it.

It would be nice if it were possible to be immediately invited to all rooms of a guild upon bridging it, instead of waiting for a message to be sent in each one.

**Comment by Sorunome** [comment]
What about `listchannels` and then clicking the pills to join? Kinda worried users reporting the opposite bug if implementing this, like "I just bridged a guild and now i got spammed with 40 invites"

**Comment by anoadragon453** [comment]
You could do that and additionally prompt the user with:

"If you would like to be invited to all channels, use `joinallrooms <user ID> <guild ID>`"

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/63f1887ec55a9bf51420d9bbc2f4ab03c4c9e04c

Syntax is `joinentireguild <puppetId> <guildId>`
