### ISSUE TITLE
Invite user to a matrix community upon bridging a guild

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#32]
While communities are still unspecced, it would be nice for parity with Discord to be able to have a community automatically created upon bridging a guild, which the user is then invited to.

Speccing communities may be a blocker on this though.

**Comment by Sorunome** [comment]
Not sure if it is a good idea to implement this as "soon" communities as rooms are implemented? What about the ability to reserve a namespace for community IDs?

**Comment by Sorunome** [comment]
Added in https://github.com/matrix-discord/mx-puppet-discord/commit/226c4f5e6c9b1d1a028f90728d58c41d5a09ad84
