### ISSUE TITLE
DMs have 3 users in them which breaks DM display

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#33]
![image](https://user-images.githubusercontent.com/1342360/71707771-4c919e00-2dba-11ea-887c-5f97aae2c073.png)

![image](https://user-images.githubusercontent.com/1342360/71707775-54e9d900-2dba-11ea-9403-ae9942668c38.png)

DMs look a bit ugly in Riot as the discord user is also in them, which makes them a room of 3 participants instead of 2. Afaik there's 2 problems here with potential solutions:

* My discord user "Violet Ray" is in the room. They do not need to be permanently, only when I sent a message using the Discord app. Violet Ray could then join the room, send the message, then leave, fixing the room display.
* If I message someone for the first time since setting up the bridge from the discord app instead of matrix, Violet Ray becomes the admin of the matrix 1-1 room (as seen in the first picture). Instead the bridge should make sure that the puppet of the other user is always the one that is the admin (and possibly the one to create the room).

**Comment by Sorunome** [comment]
If the user leaves right after sending a message and you are having a conversation via the discord chat for a change it'd be quite the join/leave spam, not sure how to approach this

**Comment by anoadragon453** [comment]
True. Other bridges solve this by just not relaying messages if you send them on the 3rd party channel side, but I'm not sure if that's really a solution here.

Perhaps a timeout of 1hr, if the user hasn't sent a message for that long they leave the room?

**Comment by anoadragon453** [comment]
@Half-Shot has noted that since you are the only matrix user here, you can just set the name of the room to the Discord user's username (and remember to update it when the name changes).

**Comment by Sorunome** [comment]
> @Half-Shot has noted that since you are the only matrix user here, you can just set the name of the room to the Discord user's username (and remember to update it when the name changes).

Soru would highly prefer to omit that route as that pulls multiple other problems with it

**Comment by Sorunome** [comment]
> Perhaps a timeout of 1hr, if the user hasn't sent a message for that long they leave the room?

Note to self: when implementing this, make sure that that ghost puppet isn't the *only* one of the bridge in the room before leaving.

That can happen when starting a DM by tying a message via the official discord client and the other side didn't reply yet

**Comment by Sorunome** [comment]
Implemented in https://github.com/Sorunome/mx-puppet-bridge/commit/444421fdd427142e340471debf1df42653e78757

As it only triggers when you say something via the official discord channel you could just briefly do that on all the affected channels and then wait for an hour

**Comment by anoadragon453** [comment]
Thanks, will test!

**Comment by MRAAGH** [comment]
This solution where we need to wait for an hour works, but it would be even better if we had the ability to trigger this whenever we want. For example if there was a command I can type into the "Discord Puppet Bridge" room which would immediately remove all my ghosts from all my rooms?

**Comment by MRAAGH** [comment]
Is it possible that the actual Matrix account could substitute the role of the ghost? So I'd send a message using Discord, and on the Matrix side it would come from my actual Matrix account?

**Comment by Sorunome** [comment]
try turning on double puppeting, see the readme of the mx-ouopet-bridge repo for how to do that

22. 4. 2021 15:39:15 Maze ***@***.***>:
