### ISSUE TITLE
Message should be clearer when bridging a guild

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#34]
![image](https://user-images.githubusercontent.com/1342360/71707882-2ddfd700-2dbb-11ea-8171-4725cb9a138a.png)

Ignoring the typo, the message here isn't very clear. I waited around for about 30m expecting to start getting invited to rooms from the guild I just bridged, only to realize I'd only start getting invites once a message was sent. 

I've made issues about changing that behaviour anyways, but it'd be nice in this moment to explain what the user should expect from here onwards.

Something like: "Discord Puppet Bridge is now listening for messages in Guild BABSCon", which would at least clue the user in that a message needs to be sent in a room before the bridge will act upon it.

**Comment by Sorunome** [comment]
> Ignoring the typo

whaaaa, how to english? a little help, please?

Also, maybe add "Type `listchannels` and click a channel pill to start talking"?

**Comment by anoadragon453** [comment]
> whaaaa, how to english? a little help, please?

"Is now **being** bridged" :)

> Also, maybe add "Type listchannels and click a channel pill to start talking"?

Mm, I think we can just replace this step and tell people to `listchannels` instead (or have a way to auto-join all channels at once), no?

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/24ef3804fa3b6485fb43ebe31b8c72cf135c4062

**Comment by anoadragon453** [comment]
So does the bridge no longer invite you to channels as people talk in them? (I agree that this was confusing, so happy to see it removed if so).

**Comment by Sorunome** [comment]
It still does.

**Comment by anoadragon453** [comment]
Oh, well if you want to leave that behaviour in, then the message should contain "You will be invited to guild channels as messages are sent in them", just to let the user know.

**Comment by Sorunome** [comment]
done, thanks
