### ISSUE TITLE
Bridge sends "Discord Puppet Bridge" as a message before every response

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#35]
![image](https://user-images.githubusercontent.com/1342360/71708024-38e73700-2dbc-11ea-8daa-424521c716c1.png)

The bridge sends the message "Discord Puppet Bridge" before sending every response, which seems unnecessary, and also a bit confusing when an incorrect command is given:

![image](https://user-images.githubusercontent.com/1342360/71708036-4d2b3400-2dbc-11ea-9e42-24eb747c7b1d.png)

(There is information below "Links:", I'm just not showing my username).

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/dfda827da9f2ed61baee6507db4bc45ee76090bd
