### ISSUE TITLE
Ability to bridge a single channel

### ISSUE THREAD

**Issue by commagray** [matrix-discord/mx-puppet-discord#36]
Currently I use this bridge just for one channel, but it keeps inviting me in other channels.

So instead of `bridgeguild` it would be nice to have something like `bridgechannel` with syntax like:

`bridgechannel $guildid $channelid` (same as matrix-appservice-discord)

**Comment by Sorunome** [comment]
channelid is already a unique identifier. Will add this, though

**Comment by Sorunome** [comment]
Added in https://github.com/matrix-discord/mx-puppet-discord/commit/9576657e6583225c2a57b58035414b0552fa515a

Syntax is `bridgechannel $puppetId $channelId` and `unbridgechannel $puppetId $channelId`
