### ISSUE TITLE
Ability to joinentireguild without bridging the guild

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#39]
My usecase is I'd like to bridge all but one channel of a guild.

To do so, I'd like to bridge all channels of a guild, but reject the invite to the one channel I don't want to be in.

This is preferable to listing all channels in a guild and then joining each one manually.

I don't want to start bridging the guild because whenever someone sends a message in the channel I don't want to bridge, I'll get an invite from the bridge to that channel.

Currently I have to:

* Start bridging the guild
* bridgeentireguild the guild
* Reject the one invite
* Stop bridging the guild

Ideally I would be able to do step 2 without needing to do step 1 first.

**Comment by Sorunome** [comment]
as soon as you stop brudging messages won't get sent around anymore. This isn't what you want.

Am 6. Januar 2020 06:01:31 MEZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by Sorunome** [comment]
For now it'd be easiest for you to just join that room and stick it in low priorty or something. Once room knocking is a thing soru is planning to revampt the way the invite system works to make it better

**Comment by anoadragon453** [comment]
> as soon as you stop brudging messages won't get sent around anymore. This isn't what you want

Yep, just learned this the hard way :D

Ok, thanks for the explanation. I better get on that knocking MSC then :)

**Comment by Sorunome** [comment]
@anoadragon453 is it OK to close this issue?

**Comment by Sorunome** [comment]
Until knock is a thing, you can now

`setautoinvite <puppetId> 0` and then, to get access to a room, `invite <invitabel thing>`, where the invitable thing is a room id, room alias, user id or matrix.to URI

**Comment by anoadragon453** [comment]
> @anoadragon453 is it OK to close this issue?

Oops, sorry for missing this.

Thank you for tackling this, much appreciated :)
