### ISSUE TITLE
different behaviour when staring a chat or someone else does

### ISSUE THREAD

**Issue by BrainDamage** [matrix-discord/mx-puppet-discord#40]
I am using mx-puppet-discord as a double-puppeted bridge

If I join a room myself, then _discordpuppet_bot will show enter/show itself and the online status of the users will reflect the one on discord.
If I bridge a guild and someone sends a message to a chat, I'll be prompted to join the chatroom, if I do, the bot won't be listed among the nicks, also, I'm not 100% sure of this but I think in such condition the user status will be based off chat activity rather than user status in discord

**Comment by Sorunome** [comment]
This is intended behaviour. The bot isn't in the discord side, either, though, so whenever possible it won't be in the room. Ghost statuses still accurately reflect those of the users in discord.

Am 6. Januar 2020 13:50:07 MEZ schrieb BrainDamage <notifications@github.com>:

**Comment by BrainDamage** [comment]
So I should not join a room, but rather wait for someone else to speak to prevent having a "useless" bot in the nicklist? Can the bot quit the room once a user speaks, so that there'll be more than one participant?

**Comment by Sorunome** [comment]
If you are up-to-date it should auto-quit as new ghosts join. If not, that's a bug.

Am 6. Januar 2020 16:48:19 MEZ schrieb BrainDamage <notifications@github.com>:

**Comment by BrainDamage** [comment]
![screenshot](https://user-images.githubusercontent.com/50474/71871902-125a3080-311b-11ea-8185-bc3c30fd798d.jpg)

I apologize for the italian, but it should show that once a user joins the channel, it doesn't remove the bot
my version hash is 226c4f5

**Comment by Sorunome** [comment]
do you have any log output for when the other ghost joins? Just tried and here the bot user leaves the room (as it should)

**Comment by Sorunome** [comment]
@BrainDamage do you have any logs? Just re-tried and it works locally, that the appservice bot leaves once a ghost joins.

**Comment by BrainDamage** [comment]
After trying latest version, I cannot reproduce the bug anymore.
I apologize for not replying for so long, I've missed the notification and forgot about the issue.

**Comment by Sorunome** [comment]
Don't worry, and thank you for reporting it originally ^^
