### ISSUE TITLE
Ability to join a guild via an invite link

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#41]
I was sent an invite link in a chat. Unfortunately this means I need to open Discord to join the server via the link. Ideally I could just `joinlink 1 <link>` to the bot and join the server that way.

**Comment by Sorunome** [comment]
Added in https://github.com/matrix-discord/mx-puppet-discord/commit/79434d7eef71ef6155b1688ca797ff4c09d414d9

Syntax is `acceptinvite $puppetId $invite` where the invite can be a discord.gg URL, a discordapp.com/invite URL or just the plain invite ID
