### ISSUE TITLE
Friend management: Added/sent friend request to undefined!

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#42]
Added a friend with the command `addfriend 1 [redacted]#1234`

Adding the friend was successful! However the response was the following:

```
Added/sent friend request to undefined!
```

Relavent logs:
```
Jan 13 00:10:31 synapse npm[7713]: Jan-13 00:10:31.897 [BotProvisioner] info: Got message to process with arg=addfriend
Jan 13 00:10:31 synapse npm[7713]: ---------------
Jan 13 00:10:31 synapse npm[7713]: null
Jan 13 00:10:31 synapse npm[7713]: (node:7756) DeprecationWarning: ClientUser#addFriend: userbot methods will be removed
Jan 13 00:10:32 synapse npm[7713]: [redacted]#1234
```

Also should it say "Sent friend request to ..." instead of "Added/sent ..." ?

**Comment by Sorunome** [comment]
> Also should it say "Sent friend request to ..." instead of "Added/sent ..." ?

No, as you use the same command to accept an incoming friends request, in which case you add that friend

**Comment by Sorunome** [comment]
Also, the bug was an oversight where if your client never talked with that other user yet it doesn't have the discord user, only the username#discriminator string.

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/d438f835aeb9385f5673abdedfce052c4558e665
