### ISSUE TITLE
After invited to a DM by your own Discord account, a room of 3 is created

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#44]
# Steps to reproduce:
1. have a user token bridge
2. have a DM on discord which is not bridged to Matrix yet, because it wasn't used since the moment the user token bridge was created
3. send a message in that DM using the Discord app (from your own account)
4. you will get an invitation on Matrix
5. accept on Matrix
6. notice that the room on Matrix currently has 2 participants and both of them are you
7. when the other person in the DM says something, they appear in the Matrix room.

# What I expected to happen:
The Matrix room should get the picture and the name of the person I am speaking to. And there shouldn't be two of me in the room.

# What is actually happening:
The Matrix room keeps the default name (which is an awfully long list of usernames) and picture (which is my own picture). And that puppet which apparently represents my discord account stayed in the room, it didn't automatically leave, even after multiple hours. It would be best if this member was not there in the first place.

**Comment by Sorunome** [comment]
> The Matrix room should get the picture and the name of the person I am speaking to.

Client bug / will be fixed with canonical DMs

> And there shouldn't be two of me in the room.

As discussed in #33 this is necessary, the ghost will leave when it can in about an hour.
