### ISSUE TITLE
When the bridge fails to make groups, you'll miss the first message of a newly joined bridge room

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#46]
The matrix user is losing a message here:

* Bridge a guild
* Send a message in a room from discord
* Matrix user receives an invite to a room which has no messages in it
* Send another message in the room from discord
* Matrix user receives the second message

They never got the first and have to open Discord to see it.

**Comment by Sorunome** [comment]
> Send a message in a room

from discord or matrix?

> Send another message in the room

same question

**Comment by anoadragon453** [comment]
Apologies, have updated the original message.

**Comment by anoadragon453** [comment]
I've learned that this is only a problem when the bridge tries and fails to create groups as it is not an admin user and `enable_group_creation: false` is set in the homeserver.yaml.

**Comment by Sorunome** [comment]
should `bridge.enableGroupSync` be `false` instead of `true` by default to make the user read docs when enabling that feature?

**Comment by anoadragon453** [comment]
Yes

**Comment by Sorunome** [comment]
Config is defaulted to false now
