### ISSUE TITLE
Group DMs have a canonical alias set which messes up the room name

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#49]
Group DMs currently look like the following in my room list:

![image](https://user-images.githubusercontent.com/1342360/73380356-cc2c6300-42bb-11ea-9fe7-e8a3849685a1.png)

Even though the users inside have displaynames properly set, Riot seems to take the canonical alias as a method of calculating the room name when one isn't set.

A fix would be to set `#_discordpuppet...` as an alias of the room, but not the canonical alias, if that's possible.

**Comment by Sorunome** [comment]
Ironically this is the same issue as https://github.com/Sorunome/mx-puppet-slack/issues/6

Removing the canonical alias and having it just as a normal alias still means you can make channel pills and stuffs out of it, correct?

**Comment by anoadragon453** [comment]
It won't tab complete (but who's going to type `_discordpuppet_...` anyways), but it will pill if you send it in a formatted message like you would any other pill.

**Comment by anoadragon453** [comment]
So looks like Riot is still going to display non-canonical aliases of a room as the room name, which means we can't attach an alias to a room (for linking purposes) and name the room after the room members.

**Comment by Sorunome** [comment]
> It won't tab complete (but who's going to type `_discordpuppet_...` anyways), but it will pill if you send it in a formatted message like you would any other pill.

tab complete currently works if you do like `#main<tab>`, though

**Comment by anoadragon453** [comment]
> > It won't tab complete (but who's going to type `_discordpuppet_...` anyways), but it will pill if you send it in a formatted message like you would any other pill.
> 
> tab complete currently works if you do like `#main<tab>`, though

So it does!

**Comment by Sorunome** [comment]
Should be fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/f117e6eae21a6bb7baaedaf9950c3d1488120ecf

So only riot needs updating to keep those in mind when doing tab-completion

**Comment by anoadragon453** [comment]
Super happy, thank you :)
