### ISSUE TITLE
Add a setting that controls whether to add ghost users for all discord users

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-discord/mx-puppet-discord#5]
By default, mx-puppet-discord appears to create a matrix ghost user for every discord user across every guild that is available with the user/bot token provided, as opposed to only adding users that appear in your DMs. Given the size of many discord guilds -- We're not dealing with something more reasonably sized like iMessage or hangout group chats -- this could mean many thousands or even tens of thousands of user records are being created on the HS. It would probably be best if there were a setting like addAllDiscordUsers in the config.yaml (False by default with a big fat warning somewhere letting you know the implications of enabling it) that controls this behavior. In the case of `False`, it would only add corresponding matrix ghost users for users that are in your DMs. `True` would use the current behavior.

**Comment by Sorunome** [comment]
You can disable presence with `presence.enabled = false`.

Updated the core library to only update presence on already registered ghosts
