### ISSUE TITLE
embeds from discord will not bridge to matrix

### ISSUE THREAD

**Issue by j0w0** [matrix-discord/mx-puppet-discord#50]
I have not ever seen them send at all

![discord-1](https://matrix.catgirl.party/_matrix/media/r0/download/catgirl.party/PtZwitzRQaXjeGgUkcViyVkL)
   |
   \\/
![matrix-1](https://matrix.catgirl.party/_matrix/media/r0/download/catgirl.party/xPjjiTFAKKmTPgpbXXyYGWUB)

(picture of same room from matrix, the starry is background is just my discord theme)
![matrix-2](https://matrix.catgirl.party/_matrix/media/r0/download/catgirl.party/NCTPrxRoFTNeNTTVqxayfJUX)

**Comment by Sorunome** [comment]
Issue was actually embeds but blank body. Anyhow, fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/8f22436f6ac620e8637430c24931ae7fc40c7bd5
