### ISSUE TITLE
Questions regarding group rooms (how to: rejoin? re-create?)

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-discord/mx-puppet-discord#58]
I have a group dm room that was acting oddly. I'd like to completely dis-associate the group room from mx-puppet-discord so that mx-puppet-discord creates it again from scratch. How do I do this? Thanks!

**Comment by Sorunome** [comment]
`unbridge @_discordpuppet_thatwholemxid:yourserver.com`

**Comment by Sorunome** [comment]
In which way was it acting oddly, though?

**Comment by AndrewJDR** [comment]
Thanks, I ran unbridge and it said "Unbridged the room!", but when i run `listrooms`, the room is still displayed in the list.

The oddity with the room:
The room had an odd name (like "__discordpuppet_some_weird_room_name"), and I wanted to give the room a friendlier name, but my matrix user didn't have any kind of administrative access to it. The room was created prior to me properly running `setmatrixtoken`, so I was hoping to kill and recreate the room entirely so I could confirm whether that's what caused the lack of permissions and odd room name, or if there's some unrelated issue happening.

**Comment by AndrewJDR** [comment]
Okay, after restarting the bridge, it has now created the new room (using the same alias as before). Things are looking overall better, because there's no longer an extra ghost user in the room. However, the room name is still cryptic (`#_discordpuppet_<some number>`), and my matrix user was not given any admin privileges on the room, so I'm not sure how to give it a nicer name...

**Comment by AndrewJDR** [comment]
Ah, at this point this seems to be a duplicate of https://github.com/matrix-discord/mx-puppet-discord/issues/26

Closing this.

**Comment by Sorunome** [comment]
Actually it's a duplicate of #49

Am 9. März 2020 08:22:47 MEZ schrieb Andrew Johnson <notifications@github.com>:
