### ISSUE TITLE
Unable to create room when sending a message with the bridged discord account (double-puppeting)

### ISSUE THREAD

**Issue by Randshot** [matrix-discord/mx-puppet-discord#59]
[Message](https://matrix.to/#/!uOjvskgRfNgksdiArw:sorunome.de/$0OZ7vI0LTBMWc_MUSQ0ixOLcTeks_QkQHIWwR_ccD98?via=sorunome.de&via=matrix.org) from the Matrix discussion:

> I noticed a bug recently, where when you use double-puppeting with the discord bridge, it fails to create a new room for bridged channels/guilds when you use your bridged discord account to send a message in said channel. According to the logs, it tries to create a room with a `#_discordbot_` alias with the puppet-ed matrix account, but since that namespace is reserved for the discord bridge appservice, the server returns an `M_EXCLUSIVE` error.

_Btw, I also tried the same with double-puppetting disabled, and it works like expected._

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/eed18589147ec680d3d68d2f5305ce4ae73e1518
