### ISSUE TITLE
direct chats have wrong room avatar because of matrix puppet

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#77]
When no double puppeting is configured and you write something in discord, your discord user joins the matrix room which results in something like this:

![image](https://user-images.githubusercontent.com/1029578/83967949-dabc0400-a8c5-11ea-9d68-905c660d606c.png)

For DM's that means the room can get the wrong room avatar and room name

I think it'd make sense to either leave matrix room with the discord user after sending the message or set the room avatar + room name to the same as the other discord user's displaname/avatar.

**Comment by Sorunome** [comment]
Send something from the matrix end, wait an hour and the room will have fixed itself :)

**Comment by Sorunome** [comment]
The 1h timeout exists as to not spam join/leaves

**Comment by lub** [comment]
Aaand it fixed itself, thank you very much :)
