### ISSUE TITLE
acceptinvite joins guild, but reports failure with "this.guilds.get is not a function"

### ISSUE THREAD

**Issue by Sorixelle** [matrix-discord/mx-puppet-discord#79]
Passing a valid puppet ID and Discord invite (ie. `acceptinvite 1 https://discord.gg/<code>`) results in the following output from the bridge:

> Invalid invite code `<code>`: this.guilds.get is not a function

The server is successfully joined, however, despite the error from the bridge implying it wasn't.

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/better-discord.js/commit/5e58e1e7510cf2192f3503ca146dd61a56a75c72
