### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by izissise** [matrix-discord/mx-puppet-discord#80]
Hello,

It would be great if mx-puppet-discord would provid an automated build on docker hub from the current repo.

**Comment by Sorunome** [comment]
Unfortunately dockerhub doesn't play nice and doesn't allow soru to select this repo :(

**Comment by jdreichmann** [comment]
I tried to reproduce this, but couldn't. I forked the repo and docker-hub let me setup a build just like normal:
https://hub.docker.com/repository/registry-1.docker.io/transcaffeine/mx-puppet-discord/builds/643f8fc1-c26b-4e88-ada5-9524d21e1e47

Is it still not working or can the community help in troubleshooting this problem?

**Comment by spantaleev** [comment]
The above link was asking for you to sign in.

Here's a link to the image on Docker Hub: https://hub.docker.com/r/transcaffeine/mx-puppet-discord

Perhaps we could switch to that image and merge this?

**Comment by jdreichmann** [comment]
That would require setting up that the fork i created always follows master of the upstream - which is doable, but not really pretty, unfortunately.

**Comment by Sorunome** [comment]
The problem is that dockerhub doesn't allow soru to even select the matrix-discord organisation

**Comment by jdreichmann** [comment]
And you grated dockerhub access to the org, as shown in https://docs.docker.com/docker-hub/builds/link-source/#grant-access-to-a-github-organization or did this not show up when you first connected your Github-Account?

**Comment by Sorunome** [comment]
The org didn't show up yet when first connecting and it never re-asked

**Comment by jdreichmann** [comment]
The section about manually granting DockerHub access on a GitHub-Org is not working either? There is a section right below about how to do that

**Comment by Sorunome** [comment]
That did the trick, thanks a lot! It wasn't exactly how described there, but soru figured it out. You can find it here now: https://hub.docker.com/repository/docker/sorunome/mx-puppet-discord
It's prolly sitll building ^^

**Comment by jdreichmann** [comment]
Amazing, awesome that it worked out! I tried to setup it either in order to better understand the problem and GitHub+DockerHub is sometimes tricky. Wenn the Builds are working, @spantaleev can point the used playbook image to this :)

**Comment by Ryonez** [comment]
@Sorunome May I ask how you built the image?
I'm trying to make some small changes to get #186 myself. However I'm unable to get the image to work. Knowing how the official one is being put together might help a lot.

**Comment by lub** [comment]
@Ryonez I'm not Soru, but did you have a look at https://github.com/matrix-discord/mx-puppet-discord/blob/master/Dockerfile ?

**Comment by Ryonez** [comment]
Yes, this is what I'm using to try and build it.

**Comment by Sorunome** [comment]
it's just dockerhub doing its thing, soru never actually did that herself, others always helped

**Comment by Ryonez** [comment]
Hek, alrighty. I'll poke it and see if I can get it to work my end.
