### ISSUE TITLE
status sometimes gets set multiple times

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#81]
I don't know what causes this. It doesn't happen when you manually set a custom status.

As you can see replaces_state is the same in every event update.

![image](https://user-images.githubusercontent.com/1029578/84687249-b30c1200-af3d-11ea-993f-6dc19064c64b.png)

**Comment by Sorunome** [comment]
As you can see, it switches between containing an registered trademark symbol and not (r), as such the bridge is doing exactly what it is supposed to do. In a future update the status state events are disabled by default, the status message is still visible via the presence module, though.
