### ISSUE TITLE
status doesn't reset

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#82]
When someone has a status message in discord (e.g. playing a game or a custom status) it gets synced to matrix, but an empty status isn't getting synced.

Steps to reproduce:

1. set custom status in discord
2. status message in matrix changes
3. remove custom status in discord
4. status message in matrix stays the same instead of <empty string or whatever>

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/0458ab6d5039f84f7bc2fa1be341d9c47994aaa2
