### ISSUE TITLE
Mentions don't notify me in Element Web

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#89]
This may be more an element web problem, but pills that *look* like they're directed to my user don't actually notify me. Either due to the inner html of the pill or the message body not including my username:

![image](https://user-images.githubusercontent.com/1342360/88998110-3664a580-d2e9-11ea-9ff2-a1fe92652f37.png)

Notice there is no highlight. No highlight appears in the room list either.

The source:

![image](https://user-images.githubusercontent.com/1342360/88998127-3fee0d80-d2e9-11ea-9607-f89e83b8eb10.png)

**Comment by Sorunome** [comment]
It is because the message body does not include your username. You could add "Violet Ray" to your keywords to ping you

This seems to be more an issue with matrix ping system, and thus as an extension push rules, in general :/

**Comment by anoadragon453** [comment]
Thanks for the clarification. Should the bridge not replace the Discord nick with the matrix displayname though?

**Comment by Sorunome** [comment]
Why that? The display name in that room is a more accurate representation. Instead notifications should look for mention pills (and ideally have a way to *only* get a ping via a pill, not via just plaintext mention, but that discussion is off-scope for this issue)

**Comment by anoadragon453** [comment]
I was thinking that it would be correct for the bridge to translate Discord elements in the `body` to Matrix ones, but after a quick discussion with @Half-Shot, we came to the conclusion that in an ideal world the bridge wouldn't translate that, and Matrix users would still get pinged. This seems to be what you were getting at, and I respect your choice if you don't want to do a temp fix and instead wait for notifications to improve.

From a user's perspective I would enjoy the temp fix of course. But I don't mind if you want to wait for a proper fix instead.

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-discord/matrix-discord-parser/commit/52592702afd3fb9e9305f04b785a0001e59f1ef1
