### ISSUE TITLE
Discord account is always online

### ISSUE THREAD

**Issue by MRAAGH** [matrix-discord/mx-puppet-discord#98]
When using mx-puppet-discord with user token, and also when using it with a bot, the Discord account or bot constantly appears online. It would be nice if the status switched between "online" and "invisible" depending on what's going on on Matrix!

**Comment by Sorunome** [comment]
This requires https://github.com/matrix-org/matrix-doc/pull/2409

**Comment by MRAAGH** [comment]
So for bridging anything besides messages, we need that PR?

**Comment by Sorunome** [comment]
basically, yes

**Comment by MRAAGH** [comment]
It's surprising Matrix doesn't have that since a long time ago; since it was designed with bridges in mind

**Comment by Sorunome** [comment]
added in https://github.com/matrix-discord/mx-puppet-discord/commit/0a21bb8ad5b9c41ad346de99df5a38d384d9c9ef
